### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sandric** [mopemope/meghanada-server#2]
I tried to install meghanada server from emacs and by compiling from source via gradlew - both times it is successfull, but when I try to run `java -jar meghanada.jar` I'm getting

```
sandric@sandric-mac ~/meghanada-server> java -jar build/libs/meghanada.jar
Exception in thread "main" java.lang.NullPointerException
       	at java.util.Hashtable.put(Hashtable.java:459)
       	at java.util.Properties.setProperty(Properties.java:166)
       	at java.lang.System.setProperty(System.java:796)
       	at meghanada.Main.main(Main.java:35)
```

Here's my java version:
```
sandric@sandric-mac ~/meghanada-server> java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by mopemope** [comment]
I tried build jar, but couldn't reproduce it.
Please check your `MANIFEST.MF`.

**Comment by sandric** [comment]
@mopemope Hm I don't see any `MANIFEST.MF` in my local directory, only `Manifest.param` file. Can you tell me where should I look for it please?

**Comment by mopemope** [comment]
Please try again `shadowJar`
```
./gradlew clean shadowJar
```

And check following file.
```
./build/tmp/shadowJar/MANIFEST.MF
```

**Comment by sandric** [comment]
@mopemope Ok, I recompiled and here's MANIFEST.MF file:
```
sandric@sandric-mac ~/meghanada-server> cat build/tmp/shadowJar/MANIFEST.MF
Manifest-Version: 1.0
Date: 2016-09-08T16:44:47+0300
Version: 0.1.0-620444b
Main-Class: meghanada.Main
```

**Comment by ejemba** [comment]
@mopemope Hi , I have the same issue.
I'm running on linux archlinux.
My manifest looks fine

```
Manifest-Version: 1.0
Date: 2016-09-09T09:58:49+0900
Version: 0.1.0-f5d3113
Main-Class: meghanada.Main
```
My java version
``` 
java -version 
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
```
The error
```
java -jar ~/.meghanada/meghanada.jar --help
Exception in thread "main" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at meghanada.Main.main(Main.java:35)
```

**Comment by mopemope** [comment]
@ejemba @sandric  Hmm. I can't reproduce it ...
Do you use gradle wrapper ?

**Comment by ejemba** [comment]
@mopemope yes I used gradle wrapper.
I identified the problem I think, with  our configuration.

https://github.com/mopemope/meghanada-server/blob/master/src/main/java/meghanada/Main.java#L30
```
return mainAttributes.getValue("Version");
```
does return null rather what we found in the Manifest.Mf 

I was wondering if the correct key to use shouldn't be : Attributes.Name.MANIFEST_VERSION rather than "Version" ?

**Comment by ejemba** [comment]
@mopemope yes I used gradle wrapper.
I identified the problem I think, with  our configuration.

https://github.com/mopemope/meghanada-server/blob/master/src/main/java/meghanada/Main.java#L30
```
return mainAttributes.getValue("Version");
```
does return null rather what we found in the Manifest.Mf 

I was wondering if the correct key to use shouldn't be : `Attributes.Name.MANIFEST_VERSION` rather than "Version" ?
